name: CI/CD to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  AR_REGION: ${{ secrets.AR_REGION }}
  AR_REPOSITORY: ${{ secrets.AR_REPOSITORY }}
  CLOUD_RUN_SERVICE_NAME: ${{ secrets.CLOUD_RUN_SERVICE_NAME }}
  CLOUD_RUN_REGION: ${{ secrets.CLOUD_RUN_REGION }}
  IMAGE_NAME: vitrine-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Google Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Configure Docker to use Google Artifact Registry
        run: gcloud auth configure-docker ${AR_REGION}-docker.pkg.dev

      - name: Build and push Docker image to Artifact Registry
        run: |
          docker build -t ${AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPOSITORY}/${IMAGE_NAME}:${{ github.sha }} .
          docker push ${AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPOSITORY}/${IMAGE_NAME}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${CLOUD_RUN_SERVICE_NAME} \
            --image ${AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPOSITORY}/${IMAGE_NAME}:${{ github.sha }} \
            --region ${CLOUD_RUN_REGION} \
            --platform managed \
            --allow-unauthenticated # Remova ou ajuste conforme a necessidade de autenticação
            --port 3000
            --memory 512Mi
            --cpu 1
            --min-instances 1
            --max-instances 1
